BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[UserInfo] (
    [id] INT NOT NULL IDENTITY(1,1),
    [firstName] NVARCHAR(1000),
    [lastName] NVARCHAR(1000),
    [email] NVARCHAR(1000) NOT NULL,
    [password] NVARCHAR(1000) NOT NULL,
    [age] INT NOT NULL,
    [role] NVARCHAR(1000),
    CONSTRAINT [UserInfo_pkey] PRIMARY KEY CLUSTERED ([id]),
    CONSTRAINT [UserInfo_email_key] UNIQUE NONCLUSTERED ([email])
);

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
